version = 1
SPDX-PackageName = "Gardener terraformer"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/terraformer"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "vendor/github.com/google/gnostic/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/gnostic contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/cespare/xxhash/v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/cespare/xxhash/v2 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/modern-go/reflect2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/modern-go/reflect2 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/gobuffalo/flect/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/gobuffalo/flect contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/golang.org/x/time/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/time contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/prometheus/client_golang/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/client_golang contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/golang/mock/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang/mock contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/component-base/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/component-base contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/prometheus/client_model/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/client_model contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/evanphx/json-patch/v5/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/evanphx/json-patch/v5 contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/code-generator/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/code-generator contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/sigs.k8s.io/controller-runtime/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 sigs.k8s.io/controller-runtime contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/go.uber.org/zap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.uber.org/zap contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/spf13/cobra/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/spf13/cobra contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/apimachinery/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/apimachinery contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/google/pprof/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/pprof contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/apimachinery/third_party/forked/golang/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/apimachinery/third_party/forked/golang contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/pkg/errors/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/pkg/errors contributors."
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = "vendor/github.com/prometheus/common/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/common contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "LICENSES/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 LICENSES contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/golang.org/x/term/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/term contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/onsi/gomega/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/gomega contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/k8s.io/apiextensions-apiserver/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/apiextensions-apiserver contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/onsi/ginkgo/v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/ginkgo/v2 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/ahmetb/gen-crd-api-reference-docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/ahmetb/gen-crd-api-reference-docs contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/emicklei/go-restful/v3/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/emicklei/go-restful/v3 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/spf13/afero/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/spf13/afero contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/text/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/text contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/matttproud/golang_protobuf_extensions/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/matttproud/golang_protobuf_extensions contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/oauth2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/oauth2 contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/russross/blackfriday/v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/russross/blackfriday/v2 contributors."
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = "vendor/k8s.io/gengo/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/gengo contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/golang/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/golang/groupcache/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang/groupcache contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/jmespath/go-jmespath/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/jmespath/go-jmespath contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/klog/v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/klog/v2 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/spf13/pflag/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/spf13/pflag contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/go.uber.org/multierr/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.uber.org/multierr contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/k8s.io/klog/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/klog contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/go-task/slim-sprig/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/go-task/slim-sprig contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/fsnotify/fsnotify/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/fsnotify/fsnotify contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/google/gofuzz/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/gofuzz contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/sys/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/sys contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/go-logr/logr/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/go-logr/logr contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/utils/internal/third_party/forked/golang/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/utils/internal/third_party/forked/golang contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/hashicorp/errwrap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/hashicorp/errwrap contributors."
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "vendor/go.uber.org/atomic/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.uber.org/atomic contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/google/go-cmp/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/go-cmp contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/beorn7/perks/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/beorn7/perks contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/google/uuid/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/uuid contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/bronze1man/yaml2json/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/bronze1man/yaml2json contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/Masterminds/semver/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/Masterminds/semver contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/golang.org/x/net/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/net contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/client-go/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/client-go contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/inconshreveable/mousetrap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/inconshreveable/mousetrap contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/mattn/go-colorable/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/mattn/go-colorable contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/mattn/go-isatty/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/mattn/go-isatty contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/munnerz/goautoneg/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/munnerz/goautoneg contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/aws/aws-sdk-go/internal/sync/singleflight/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/aws/aws-sdk-go/internal/sync/singleflight contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/gomodules.xyz/jsonpatch/v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gomodules.xyz/jsonpatch/v2 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/google.golang.org/appengine/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 google.golang.org/appengine contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/sigs.k8s.io/structured-merge-diff/v4/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 sigs.k8s.io/structured-merge-diff/v4 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/json-iterator/go/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/json-iterator/go contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/josharian/intern/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/josharian/intern contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/hashicorp/go-multierror/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/hashicorp/go-multierror contributors."
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "vendor/gopkg.in/yaml.v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/yaml.v2 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/gopkg.in/yaml.v3/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/yaml.v3 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/google.golang.org/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 google.golang.org/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/api/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/api contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/sigs.k8s.io/controller-tools/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 sigs.k8s.io/controller-tools contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/go-openapi/swag/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/go-openapi/swag contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/mailru/easyjson/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/mailru/easyjson contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/sigs.k8s.io/controller-runtime/tools/setup-envtest/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 sigs.k8s.io/controller-runtime/tools/setup-envtest contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/imdario/mergo/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/imdario/mergo contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/k8s.io/utils/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/utils contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/mod/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/mod contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/davecgh/go-spew/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/davecgh/go-spew contributors."
SPDX-License-Identifier = "ISC"

[[annotations]]
path = "vendor/golang.org/x/tools/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/tools contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/go-openapi/jsonpointer/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/go-openapi/jsonpointer contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/gogo/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/gogo/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/go-logr/zapr/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/go-logr/zapr contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/go-openapi/jsonreference/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/go-openapi/jsonreference contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/code-generator/third_party/forked/golang/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/code-generator/third_party/forked/golang contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/prometheus/procfs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/procfs contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/k8s.io/kube-openapi/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/kube-openapi contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/aws/aws-sdk-go/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/aws/aws-sdk-go contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/modern-go/concurrent/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/modern-go/concurrent contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/sigs.k8s.io/json/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 sigs.k8s.io/json contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/fatih/color/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/fatih/color contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/k8s.io/kube-openapi/pkg/validation/spec/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 k8s.io/kube-openapi/pkg/validation/spec contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/blang/semver/v4/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/blang/semver/v4 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/gopkg.in/inf.v0/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/inf.v0 contributors."
SPDX-License-Identifier = "BSD-3-Clause"
